swagger: '2.0'
info:
  version: 0.1.0
  title: eWaterCycle Experiment Launcher
  description: Webservice to generate and launch a Jupyter notebook
consumes:
  - application/json
produces:
  - application/json
  - application/problem+json
securityDefinitions:
  basic:
    type: basic
paths:
  /hello:
    post:
      summary: Notebook that prints Hello World
      parameters:
        - in: body
          name: request
          description: The notebook to create
          schema:
            $ref: '#/definitions/HelloRequest'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/NotebookResponse'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /opendap:
    post:
      summary: Notebook that opens an opendap URL with xarray
      parameters:
        - in: body
          name: request
          description: The notebook to create
          schema:
            $ref: '#/definitions/OpendapRequest'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/NotebookResponse'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /threeclickscience:
    post:
      summary: Three clicks to a science usecase
      parameters:
        - in: body
          name: request
          description: The notebook to create
          schema:
            $ref: '#/definitions/ThreeClickScienceRequest'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/NotebookResponse'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /bmi:
    post:
      summary: Run model on parameter set using BMI
      parameters:
        - in: body
          name: request
          description: The notebook to create
          schema:
            $ref: '#/definitions/BmiRequest'
      responses:
        201:
          description: Created
          schema:
            $ref: '#/definitions/NotebookResponse'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  NotebookResponse:
    type: object
    properties:
      location:
        type: string
        format: uri
        description: URL of experiment notebook on Jupyter Lab server
    required:
    - location
    additionalProperties: false
  HelloRequest:
    type: object
    properties:
      notebook:
        $ref: '#/definitions/NotebookRequest'
    required:
      - notebook
    additionalProperties: false
  OpendapRequest:
    type: object
    properties:
      opendap:
        type: string
        format: uri
        description: URL of opendap endpoint
      notebook:
        $ref: '#/definitions/NotebookRequest'
    required:
      - notebook
      - opendap
    additionalProperties: false
  ThreeClickScienceRequest:
    type: object
    properties:
      setup:
        type: object
        properties:
          model:
            type: string
            description: Model identifier
          region:
            type: string
            description: Region identifier, eg. hydroshed id
          period:
            type: object
            properties:
              start:
                type: string
                format: date-time
              end:
                type: string
                format: date-time
            required:
              - start
              - end
            additionalProperties: false
        required:
          - model
          - region
          - period
        additionalProperties: false
      notebook:
        $ref: '#/definitions/NotebookRequest'
    required:
      - notebook
      - setup
    additionalProperties: false
  BmiRequest:
    type: object
    required:
      - notebook
      - setup
    additionalProperties: false
    properties:
      notebook:
        $ref: '#/definitions/NotebookRequest'
      setup:
        type: object
        required:
          - model
          - parameterset
          - docker
          - var2plot
        additionalProperties: false
        properties:
          model:
            type: string
            description: Model identifier
          parameterset:
            type: string
            description: Parameter set name
          docker:
            type: string
            description: Docker image name
          var2plot:
            type: string
            description: Variable to plot
          step:
            type: integer
            description: Number of time steps to evolve model
            default: 100
  NotebookRequest:
    type: object
    required:
      - directory
    properties:
      directory:
        type: string
        description: Name of directory inside Jupyter Lab
      filename:
        type: string
        description: Name of notebook
        default: experiment.ipynb
    additionalProperties: false
  Error:
    type: object
    description: >-
      Problem Details for HTTP APIs, see
      https://tools.ietf.org/html/draft-ietf-appsawg-http-problem-00
    properties:
      status:
        type: integer
        format: int32
      type:
        type: string
      detail:
        type: string
      title:
        type: string
    required:
      - status
      - type
      - title
      - detail
    additionalProperties: false
